name: Unit Test on PR

on:
  pull_request:
    branches: [master,feat-1]

jobs:
  unit_job:
    name: Job for Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: npm ci
      - run: echo "Running unit test"
      - run: npm test
